# Generated by Django 3.0.8 on 2022-05-11 07:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salad', models.CharField(max_length=18)),
                ('entrance', models.CharField(max_length=18)),
                ('desert', models.CharField(max_length=18)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Menu')),
            ],
        ),
    ]
